### ISSUE TITLE
Error on pip install

### ISSUE THREAD

**Issue by nbonfire** [samwhitehall/ipython-bell#7]
Tried installing this fresh since you fixed the other issue, now I get this:
```Collecting IPythonBell
  Downloading IPythonBell-0.9.9.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-FYT9qF/IPythonBell/setup.py", line 26, in <module>
        long_description=open('README.rst').read(),
    IOError: [Errno 2] No such file or directory: 'README.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-FYT9qF/IPythonBell/

**Comment by samwhitehall** [comment]
This should work now, silly mistake on my end (I included the `MANIFEST` file rather than the `MANIFEST.in` file, so the README wasn't included in the `pip` distribution).

NB. you may need to use the flag `--no-cache-dir`.
